### ISSUE TITLE
Move the API call to a simple backend

### ISSUE THREAD

**Issue by joncady** [joncady/vocaby#2]
- To offload the work that the front end is doing, create a simple hosted server (probably on heroku / firebase cloud functions)
- Endpoints:
1. /getWord

**Comment by taehyunnkim** [comment]
Hey Jon
What should the /getWords do and what should it return?

**Comment by joncady** [comment]
/getWords will return the words that a user has saved! So we haven't built in users just yet, but that'll come. We can chat about it next meeting
